### ISSUE TITLE
Add support for scram-sha-256 auth method

### ISSUE THREAD

**Issue by JuniorJPDJ** [processone/p1_pgsql#6]
It's getting pretty important this times.

**Comment by badlop** [comment]
Wasn't that implemented in https://github.com/processone/p1_pgsql/commit/3bf645ba741bf82e9d5805b0f5fce4614ecba842 ?

**Comment by JuniorJPDJ** [comment]
Probably true, ejabberd was probably just using old version on last release.

Thanks for the attention ;)
