### ISSUE TITLE
 Add support for UNIX sockets

### ISSUE THREAD

**Issue by jeroenhabets** [processone/p1_pgsql#7]
As per https://github.com/processone/ejabberd/issues/3716#issuecomment-1067761015 this library lacks support for UNIX sockets, thus blocking adding PostgreSQL UNIX socket support to ejabberd (also requested in https://github.com/processone/ejabberd/issues/3165).

Now that Erlang has (stable) UNIX socket support for a while, a.o. used by ejabberd itself, it should be feasible.

**Comment by badlop** [comment]
Ok, I wrote a small patch, it's committed in https://github.com/badlop/p1_pgsql/commit/35550c54250a4ec7cbd966f955ba4875f90b88c6

And the corresponding update in ejabberd is https://github.com/badlop/ejabberd/commit/b90e7fa26138c04ea3a3e3a5db514c7c5d0de951

With that, `ejabberd.yml` may be configured with
``` yaml
sql_server: "unix:/var/run/postgresql/.s.PGSQL.5432"
```

It worked for me, please give it a try. If you need binary installers or containers for testing, tell me.

**Comment by jeroenhabets** [comment]
Wow @badlop 🥇! Amazing response time here.

As I had never run ejabberd from source before it took my an hour to get it running as I wanted to help out testing. But then I got it to run *successfully* using both the old TCP/IP and new UNIX domain socket connection for PostgreSQL. NOTE: I just did a smoke test and my conversejs is happy with either server 👍 .

**Comment by Jieiku** [comment]
Thank you very  much for this @badlop , that is Awesome!

@jeroenhabets did you keep any notes for compiling/running from source? My instance of ejabberd is installed from a .deb file.

**Comment by jeroenhabets** [comment]
@Jieiku I did :)

My starting point was:
https://github.com/processone/ejabberd/blob/master/COMPILE.md

For the tests I did:
```
git clone git@github.com:badlop/ejabberd.git ejabberd_badlop
cd ejabberd_badlop
git checkout pgsql-unix-socket

./autogen.sh
## Depends on your config / modules of course:
./configure --enable-pgsql --enable-zlib --enable-redis  --enable-stun --enable-sip --enable-new-sql-schema 
make prod

## Copy my config for this test (make a db backup first ;)) 
sudo cp /opt/ejabberd/conf/ejabberd.yml _build/prod/rel/ejabberd/conf/ejabberd.yml
## Don't forget to edit it (e.g. sql_server: "unix:/var/run/postgresql/.s.PGSQL.5432")
_build/prod/rel/ejabberd/conf/ejabberd.yml

## Run in foreground: (shutdown using Ctrl-C then choose a)
_build/prod/rel/ejabberd/bin/ejabberdctl live
```

Hope this is of any help to you...

**Comment by badlop** [comment]
This was committed in https://github.com/processone/p1_pgsql/commit/996001d5ba0991b1cca6af22903814d4157f1627, and will be available in the next p1_pgsql release.
